# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ene/resources/main_window.ui',
# licensing of 'ene/resources/main_window.ui' applies.
#
# Created: Mon Aug 27 13:28:26 2018
#      by: pyside2-uic  running on PySide2 5.11.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_window_main(object):
    def setupUi(self, window_main):
        window_main.setObjectName("window_main")
        window_main.resize(1440, 900)
        self.centralwidget = QtWidgets.QWidget(window_main)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.widget_tab.setCursor(QtCore.Qt.ArrowCursor)
        self.widget_tab.setMouseTracking(True)
        self.widget_tab.setObjectName("widget_tab")
        self.tab_local_files = QtWidgets.QWidget()
        self.tab_local_files.setObjectName("tab_local_files")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_local_files)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stack_local_files = QtWidgets.QStackedWidget(self.tab_local_files)
        self.stack_local_files.setObjectName("stack_local_files")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stack_local_files.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stack_local_files.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stack_local_files)
        self.widget_tab.addTab(self.tab_local_files, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.widget_tab.addTab(self.tabWidgetPage2, "")
        self.tab_browser = QtWidgets.QWidget()
        self.tab_browser.setObjectName("tab_browser")
        self.combobox_season = QtWidgets.QComboBox(self.tab_browser)
        self.combobox_season.setGeometry(QtCore.QRect(0, 40, 167, 31))
        self.combobox_season.setObjectName("combobox_season")
        self.combobox_season.addItem("")
        self.combobox_season.addItem("")
        self.combobox_season.addItem("")
        self.combobox_season.addItem("")
        self.combobox_season.addItem("")
        self.label_season = QtWidgets.QLabel(self.tab_browser)
        self.label_season.setGeometry(QtCore.QRect(10, 0, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_season.setFont(font)
        self.label_season.setObjectName("label_season")
        self.label_filter = QtWidgets.QLabel(self.tab_browser)
        self.label_filter.setGeometry(QtCore.QRect(10, 190, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_filter.setFont(font)
        self.label_filter.setObjectName("label_filter")
        self.combobox_sort = QtWidgets.QComboBox(self.tab_browser)
        self.combobox_sort.setGeometry(QtCore.QRect(0, 230, 141, 31))
        self.combobox_sort.setObjectName("combobox_sort")
        self.combobox_sort.addItem("")
        self.combobox_sort.addItem("")
        self.combobox_sort.addItem("")
        self.combobox_sort.addItem("")
        self.combobox_sort.addItem("")
        self.combobox_sort.addItem("")
        self.button_sort_order = QtWidgets.QToolButton(self.tab_browser)
        self.button_sort_order.setGeometry(QtCore.QRect(140, 230, 21, 21))
        self.button_sort_order.setArrowType(QtCore.Qt.DownArrow)
        self.button_sort_order.setObjectName("button_sort_order")
        self.combobox_format = QtWidgets.QComboBox(self.tab_browser)
        self.combobox_format.setGeometry(QtCore.QRect(0, 260, 167, 31))
        self.combobox_format.setObjectName("combobox_format")
        self.combobox_format.addItem("")
        self.combobox_format.addItem("")
        self.combobox_format.addItem("")
        self.combobox_format.addItem("")
        self.combobox_format.addItem("")
        self.combobox_format.addItem("")
        self.combobox_format.addItem("")
        self.combobox_format.addItem("")
        self.combobox_status = QtWidgets.QComboBox(self.tab_browser)
        self.combobox_status.setGeometry(QtCore.QRect(0, 290, 167, 31))
        self.combobox_status.setObjectName("combobox_status")
        self.combobox_status.addItem("")
        self.combobox_status.addItem("")
        self.combobox_status.addItem("")
        self.combobox_status.addItem("")
        self.combobox_status.addItem("")
        self.combobox_streaming = QtWidgets.QComboBox(self.tab_browser)
        self.combobox_streaming.setGeometry(QtCore.QRect(0, 320, 167, 31))
        self.combobox_streaming.setObjectName("combobox_streaming")
        self.combobox_streaming.addItem("")
        self.combobox_streaming.addItem("")
        self.combobox_streaming.addItem("")
        self.combobox_streaming.addItem("")
        self.combobox_streaming.addItem("")
        self.combobox_streaming.addItem("")
        self.combobox_streaming.addItem("")
        self.combobox_streaming.addItem("")
        self.combobox_genre_tag = QtWidgets.QComboBox(self.tab_browser)
        self.combobox_genre_tag.setGeometry(QtCore.QRect(0, 350, 167, 31))
        self.combobox_genre_tag.setObjectName("combobox_genre_tag")
        self.combobox_genre_tag.addItem("")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_browser)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(200, 10, 1211, 781))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridlayout_season = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridlayout_season.setContentsMargins(0, 0, 0, 0)
        self.gridlayout_season.setObjectName("gridlayout_season")
        self.groupbox_year = QtWidgets.QGroupBox(self.tab_browser)
        self.groupbox_year.setGeometry(QtCore.QRect(0, 80, 191, 101))
        self.groupbox_year.setObjectName("groupbox_year")
        self.gridLayout = QtWidgets.QGridLayout(self.groupbox_year)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupbox_year)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupbox_year)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.spinbox_year_min = QtWidgets.QSpinBox(self.groupbox_year)
        self.spinbox_year_min.setMinimum(1950)
        self.spinbox_year_min.setMaximum(2020)
        self.spinbox_year_min.setProperty("value", 2018)
        self.spinbox_year_min.setObjectName("spinbox_year_min")
        self.gridLayout.addWidget(self.spinbox_year_min, 1, 0, 1, 1)
        self.spinbox_year_max = QtWidgets.QSpinBox(self.groupbox_year)
        self.spinbox_year_max.setMinimum(1950)
        self.spinbox_year_max.setMaximum(2020)
        self.spinbox_year_max.setProperty("value", 2018)
        self.spinbox_year_max.setObjectName("spinbox_year_max")
        self.gridLayout.addWidget(self.spinbox_year_max, 1, 1, 1, 1)
        self.widget_tab.addTab(self.tab_browser, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget_tab.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.widget_tab)
        window_main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window_main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        window_main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window_main)
        self.statusbar.setObjectName("statusbar")
        window_main.setStatusBar(self.statusbar)
        self.action_prefences = QtWidgets.QAction(window_main)
        self.action_prefences.setObjectName("action_prefences")
        self.action_open_folder = QtWidgets.QAction(window_main)
        self.action_open_folder.setObjectName("action_open_folder")
        self.actionAbout_Ene = QtWidgets.QAction(window_main)
        self.actionAbout_Ene.setObjectName("actionAbout_Ene")
        self.action_source_code = QtWidgets.QAction(window_main)
        self.action_source_code.setObjectName("action_source_code")
        self.actionHelp = QtWidgets.QAction(window_main)
        self.actionHelp.setObjectName("actionHelp")
        self.menuFile.addAction(self.action_open_folder)
        self.menuSettings.addAction(self.action_prefences)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_Ene)
        self.menuHelp.addAction(self.action_source_code)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(window_main)
        self.widget_tab.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(window_main)

    def retranslateUi(self, window_main):
        window_main.setWindowTitle(QtWidgets.QApplication.translate("window_main", "ENE", None, -1))
        self.widget_tab.setTabText(self.widget_tab.indexOf(self.tab_local_files), QtWidgets.QApplication.translate("window_main", "Local Files", None, -1))
        self.widget_tab.setTabText(self.widget_tab.indexOf(self.tabWidgetPage2), QtWidgets.QApplication.translate("window_main", "Streams", None, -1))
        self.combobox_season.setCurrentText(QtWidgets.QApplication.translate("window_main", "All", None, -1))
        self.combobox_season.setItemText(0, QtWidgets.QApplication.translate("window_main", "All", None, -1))
        self.combobox_season.setItemText(1, QtWidgets.QApplication.translate("window_main", "Winter", None, -1))
        self.combobox_season.setItemText(2, QtWidgets.QApplication.translate("window_main", "Spring", None, -1))
        self.combobox_season.setItemText(3, QtWidgets.QApplication.translate("window_main", "Summer", None, -1))
        self.combobox_season.setItemText(4, QtWidgets.QApplication.translate("window_main", "Fall", None, -1))
        self.label_season.setText(QtWidgets.QApplication.translate("window_main", "Season", None, -1))
        self.label_filter.setText(QtWidgets.QApplication.translate("window_main", "Filters", None, -1))
        self.combobox_sort.setCurrentText(QtWidgets.QApplication.translate("window_main", "Sort", None, -1))
        self.combobox_sort.setItemText(0, QtWidgets.QApplication.translate("window_main", "Sort", None, -1))
        self.combobox_sort.setItemText(1, QtWidgets.QApplication.translate("window_main", "Popularity", None, -1))
        self.combobox_sort.setItemText(2, QtWidgets.QApplication.translate("window_main", "Score", None, -1))
        self.combobox_sort.setItemText(3, QtWidgets.QApplication.translate("window_main", "Trending", None, -1))
        self.combobox_sort.setItemText(4, QtWidgets.QApplication.translate("window_main", "Favourites", None, -1))
        self.combobox_sort.setItemText(5, QtWidgets.QApplication.translate("window_main", "Date Added", None, -1))
        self.button_sort_order.setText(QtWidgets.QApplication.translate("window_main", "...", None, -1))
        self.combobox_format.setCurrentText(QtWidgets.QApplication.translate("window_main", "Format", None, -1))
        self.combobox_format.setItemText(0, QtWidgets.QApplication.translate("window_main", "Format", None, -1))
        self.combobox_format.setItemText(1, QtWidgets.QApplication.translate("window_main", "TV", None, -1))
        self.combobox_format.setItemText(2, QtWidgets.QApplication.translate("window_main", "TV Short", None, -1))
        self.combobox_format.setItemText(3, QtWidgets.QApplication.translate("window_main", "Movie", None, -1))
        self.combobox_format.setItemText(4, QtWidgets.QApplication.translate("window_main", "Special", None, -1))
        self.combobox_format.setItemText(5, QtWidgets.QApplication.translate("window_main", "OVA", None, -1))
        self.combobox_format.setItemText(6, QtWidgets.QApplication.translate("window_main", "ONA", None, -1))
        self.combobox_format.setItemText(7, QtWidgets.QApplication.translate("window_main", "Music", None, -1))
        self.combobox_status.setCurrentText(QtWidgets.QApplication.translate("window_main", "Status", None, -1))
        self.combobox_status.setItemText(0, QtWidgets.QApplication.translate("window_main", "Status", None, -1))
        self.combobox_status.setItemText(1, QtWidgets.QApplication.translate("window_main", "Releasing", None, -1))
        self.combobox_status.setItemText(2, QtWidgets.QApplication.translate("window_main", "Finished", None, -1))
        self.combobox_status.setItemText(3, QtWidgets.QApplication.translate("window_main", "Not Yet Released", None, -1))
        self.combobox_status.setItemText(4, QtWidgets.QApplication.translate("window_main", "Cancelled", None, -1))
        self.combobox_streaming.setCurrentText(QtWidgets.QApplication.translate("window_main", "Streaming On", None, -1))
        self.combobox_streaming.setItemText(0, QtWidgets.QApplication.translate("window_main", "Streaming On", None, -1))
        self.combobox_streaming.setItemText(1, QtWidgets.QApplication.translate("window_main", "Crunchyroll", None, -1))
        self.combobox_streaming.setItemText(2, QtWidgets.QApplication.translate("window_main", "Funimation", None, -1))
        self.combobox_streaming.setItemText(3, QtWidgets.QApplication.translate("window_main", "Netflix", None, -1))
        self.combobox_streaming.setItemText(4, QtWidgets.QApplication.translate("window_main", "Amazon", None, -1))
        self.combobox_streaming.setItemText(5, QtWidgets.QApplication.translate("window_main", "Hidive", None, -1))
        self.combobox_streaming.setItemText(6, QtWidgets.QApplication.translate("window_main", "Hulu", None, -1))
        self.combobox_streaming.setItemText(7, QtWidgets.QApplication.translate("window_main", "Animelab", None, -1))
        self.combobox_genre_tag.setCurrentText(QtWidgets.QApplication.translate("window_main", "Genres & Tags", None, -1))
        self.combobox_genre_tag.setItemText(0, QtWidgets.QApplication.translate("window_main", "Genres & Tags", None, -1))
        self.groupbox_year.setTitle(QtWidgets.QApplication.translate("window_main", "Year", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("window_main", "From", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("window_main", "To", None, -1))
        self.widget_tab.setTabText(self.widget_tab.indexOf(self.tab_browser), QtWidgets.QApplication.translate("window_main", "This Season", None, -1))
        self.widget_tab.setTabText(self.widget_tab.indexOf(self.tab_2), QtWidgets.QApplication.translate("window_main", "My List", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("window_main", "Fi&le", None, -1))
        self.menuSettings.setTitle(QtWidgets.QApplication.translate("window_main", "Setti&ngs", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("window_main", "Help", None, -1))
        self.action_prefences.setText(QtWidgets.QApplication.translate("window_main", "&Preferences", None, -1))
        self.action_open_folder.setText(QtWidgets.QApplication.translate("window_main", "&Open local folder", None, -1))
        self.actionAbout_Ene.setText(QtWidgets.QApplication.translate("window_main", "&About Ene", None, -1))
        self.action_source_code.setText(QtWidgets.QApplication.translate("window_main", "&Source Code", None, -1))
        self.actionHelp.setText(QtWidgets.QApplication.translate("window_main", "&Help", None, -1))

