# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ene/resources/settings_window.ui',
# licensing of 'ene/resources/settings_window.ui' applies.
#
# Created: Thu Sep  6 18:54:13 2018
#      by: pyside2-uic  running on PySide2 5.11.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_window_settings(object):
    def setupUi(self, window_settings):
        window_settings.setObjectName("window_settings")
        window_settings.resize(758, 505)
        self.settings_list = QtWidgets.QListView(window_settings)
        self.settings_list.setGeometry(QtCore.QRect(6, 6, 256, 451))
        self.settings_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.settings_list.setProperty("showDropIndicator", False)
        self.settings_list.setObjectName("settings_list")
        self.settings_menu = QtWidgets.QStackedWidget(window_settings)
        self.settings_menu.setGeometry(QtCore.QRect(270, 6, 471, 451))
        self.settings_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_menu.setObjectName("settings_menu")
        self.player = QtWidgets.QWidget()
        self.player.setObjectName("player")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.player)
        self.verticalLayout.setObjectName("verticalLayout")
        self.player_layout = QtWidgets.QFormLayout()
        self.player_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.player_layout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.player_layout.setObjectName("player_layout")
        self.label = QtWidgets.QLabel(self.player)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.player_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.player)
        self.label_2.setObjectName("label_2")
        self.player_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.player_type = QtWidgets.QComboBox(self.player)
        self.player_type.setObjectName("player_type")
        self.player_type.addItem("")
        self.player_type.addItem("")
        self.player_type.addItem("")
        self.player_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.player_type)
        self.label_3 = QtWidgets.QLabel(self.player)
        self.label_3.setObjectName("label_3")
        self.player_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.player_path = QtWidgets.QLineEdit(self.player)
        self.player_path.setFrame(True)
        self.player_path.setObjectName("player_path")
        self.player_layout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.player_path)
        self.button_browse_player = QtWidgets.QPushButton(self.player)
        self.button_browse_player.setObjectName("button_browse_player")
        self.player_layout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.button_browse_player)
        self.label_http = QtWidgets.QLabel(self.player)
        self.label_http.setObjectName("label_http")
        self.player_layout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_http)
        self.use_http = QtWidgets.QCheckBox(self.player)
        self.use_http.setEnabled(True)
        self.use_http.setText("")
        self.use_http.setObjectName("use_http")
        self.player_layout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.use_http)
        self.verticalLayout.addLayout(self.player_layout)
        self.settings_menu.addWidget(self.player)
        self.local_files = QtWidgets.QWidget()
        self.local_files.setObjectName("local_files")
        self.local_paths = QtWidgets.QListView(self.local_files)
        self.local_paths.setGeometry(QtCore.QRect(1, 44, 441, 351))
        self.local_paths.setObjectName("local_paths")
        self.label_5 = QtWidgets.QLabel(self.local_files)
        self.label_5.setGeometry(QtCore.QRect(1, 11, 91, 27))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.path_add = QtWidgets.QPushButton(self.local_files)
        self.path_add.setGeometry(QtCore.QRect(270, 400, 84, 34))
        self.path_add.setObjectName("path_add")
        self.path_remove = QtWidgets.QPushButton(self.local_files)
        self.path_remove.setGeometry(QtCore.QRect(360, 400, 84, 34))
        self.path_remove.setObjectName("path_remove")
        self.settings_menu.addWidget(self.local_files)
        self.anilist = QtWidgets.QWidget()
        self.anilist.setObjectName("anilist")
        self.formLayout = QtWidgets.QFormLayout(self.anilist)
        self.formLayout.setObjectName("formLayout")
        self.title_anilist = QtWidgets.QLabel(self.anilist)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.title_anilist.setFont(font)
        self.title_anilist.setObjectName("title_anilist")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.title_anilist)
        self.label_adult = QtWidgets.QLabel(self.anilist)
        self.label_adult.setObjectName("label_adult")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_adult)
        self.check_adult = QtWidgets.QCheckBox(self.anilist)
        self.check_adult.setText("")
        self.check_adult.setObjectName("check_adult")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.check_adult)
        self.settings_menu.addWidget(self.anilist)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(window_settings)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(270, 460, 451, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_OK = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_OK.setObjectName("button_OK")
        self.horizontalLayout.addWidget(self.button_OK)
        self.button_apply = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_apply.setObjectName("button_apply")
        self.horizontalLayout.addWidget(self.button_apply)
        self.button_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)

        self.retranslateUi(window_settings)
        self.settings_menu.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(window_settings)

    def retranslateUi(self, window_settings):
        window_settings.setWindowTitle(QtWidgets.QApplication.translate("window_settings", "Settings", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("window_settings", "Video Player", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("window_settings", "Video Player for local files:", None, -1))
        self.player_type.setItemText(0, QtWidgets.QApplication.translate("window_settings", "vlc", None, -1))
        self.player_type.setItemText(1, QtWidgets.QApplication.translate("window_settings", "mpv", None, -1))
        self.player_type.setItemText(2, QtWidgets.QApplication.translate("window_settings", "Other", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("window_settings", "Path to player: ", None, -1))
        self.button_browse_player.setText(QtWidgets.QApplication.translate("window_settings", "Browse", None, -1))
        self.label_http.setText(QtWidgets.QApplication.translate("window_settings", "Use HTTP Interface for VLC", None, -1))
        self.use_http.setToolTip(QtWidgets.QApplication.translate("window_settings", "Uses a different implementation for vlc. Enable this if you\'re having issues without it. Disable it if it causes weird behaviour", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("window_settings", "Local Files", None, -1))
        self.path_add.setText(QtWidgets.QApplication.translate("window_settings", "Add", None, -1))
        self.path_remove.setText(QtWidgets.QApplication.translate("window_settings", "Remove", None, -1))
        self.title_anilist.setText(QtWidgets.QApplication.translate("window_settings", "Anilist", None, -1))
        self.label_adult.setText(QtWidgets.QApplication.translate("window_settings", "Allow Showing Adult Content", None, -1))
        self.check_adult.setToolTip(QtWidgets.QApplication.translate("window_settings", "<html><head/><body><p>Enables the option in the media browser to show 18+ results.</p><p>Requires \'18+ Content\' enabled on anilist, under Anime &amp; Manga settings.</p></body></html>", None, -1))
        self.button_OK.setText(QtWidgets.QApplication.translate("window_settings", "OK", None, -1))
        self.button_apply.setText(QtWidgets.QApplication.translate("window_settings", "Apply", None, -1))
        self.button_cancel.setText(QtWidgets.QApplication.translate("window_settings", "Cancel", None, -1))

