language: python

cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
    - "$HOME/Library/Caches/Homebrew"

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
      python: '3.6'
    - os: linux
      dist: xenial
      sudo: false
      python: '3.7'
      env: UPLOAD_COV=true
    - os: osx
      language: objective-c
      env: PYENV_VERSION=3.6.6
    - os: osx
      language: objective-c
      env: PYENV_VERSION=3.7.0

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv qt mpv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install vlc; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install qt5-default mpv vlc xvfb -y; fi

install: 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      PYENV_ROOT="$HOME/.pyenv";
      PATH="$PYENV_ROOT/bin:$PATH";
      eval "$(pyenv init -)";
      eval "$(pyenv virtualenv-init -)";
      pyenv install -s $PYENV_VERSION;
      pyenv virtualenv $PYENV_VERSION ene;
      pyenv activate ene;
    fi
  - "make ci_setup"

script:
  - make lint
  - if [[ $UPLOAD_COV == 'true' ]]; then
      make coverage; 
    else
      make test;
    fi

notifications:
  email: false
