language: python
cache: pip
dist: xenial
os:
  - linux
  - osx

python:
  - "3.6"
  - "3.7"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt mpv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install vlc; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install qt5-default mpv vlc -y; fi

install: "make ci_setup"

script:
  - make lint
  - make test
  - make coverage

notifications:
  email: false
