language: python
cache: pip
dist: xenial

python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt install qt5-default -y

install: "make ci_setup"

script:
  - make lint
  - make test
  - make coverage

notifications:
  email: false
